data:
    feature: data256/dev/feature.csv
    label: data256/dev/label.csv
    class_indice_file: data256/metadata/class_label_indices.txt
    stratified: True

dataloader_args:
    batch_size: 32
    num_workers: 1

optimizer:
    type: AdamW
    args:
        lr: 0.001

epochs: 100

model:
    type: Crnn_256_interpolate
    args:
        ks: 3
        nl: 1

outputpath: experiments/
